export const termekLista = [
  {
    nev: "Tulipán",
    leiras: "Tavaszi hagymás növény, élénk színekben.",
    kep: "kepek/kep1.jpg",
    ar: 3000,
    ertekeles: 4.5,
  },
  {
    nev: "Ibolya",
    leiras: "Illatos, alacsony növésű tavaszi virág.",
    kep: "kepek/kep1.webp",
    ar: 2500,
    ertekeles: 4.2,
  },
  {
    nev: "Rózsa",
    leiras: "Klasszikus dísznövény, romantikus megjelenéssel.",
    kep: "kepek/kep1.jpg",
    ar: 5500,
    ertekeles: 4.8,
  },
  {
    nev: "Orchidea",
    leiras: "Elegáns szobanövény, hosszú virágzással.",
    kep: "kepek/kep1.jpg",
    ar: 8000,
    ertekeles: 4.7,
  },
  {
    nev: "Napraforgó",
    leiras: "Nagy, napot követő virág.",
    kep: "kepek/kep1.jpg",
    ar: 2000,
    ertekeles: 4.3,
  },
  {
    nev: "Liliom",
    leiras: "Illatos, nagy virágú növény.",
    kep: "kepek/kep1.jpg",
    ar: 6000,
    ertekeles: 4.6,
  },
  {
    nev: "Jázmin",
    leiras: "Erős illatú kúszónövény.",
    kep: "kepek/kep1.jpg",
    ar: 4500,
    ertekeles: 4.4,
  },
  {
    nev: "Levendula",
    leiras: "Nyugtató illatú, lila virág.",
    kep: "kepek/kep1.jpg",
    ar: 3500,
    ertekeles: 4.9,
  },
  {
    nev: "Gerbera",
    leiras: "Színes, vidám virágcsokrokhoz ideális.",
    kep: "kepek/kep1.jpg",
    ar: 3200,
    ertekeles: 4.3,
  },
  {
    nev: "Krizantém",
    leiras: "Őszi virág, sokféle színben.",
    kep: "kepek/kep1.jpg",
    ar: 2800,
    ertekeles: 4.1,
  },
  {
    nev: "Magnólia",
    leiras: "Látványos virágú fa.",
    kep: "kepek/kep1.jpg",
    ar: 9000,
    ertekeles: 4.7,
  },
  {
    nev: "Bazsarózsa",
    leiras: "Dús, illatos virágfejek.",
    kep: "kepek/kep1.jpg",
    ar: 7000,
    ertekeles: 4.8,
  },
  {
    nev: "Százszorszép",
    leiras: "Egyszerű, kedves megjelenésű virág.",
    kep: "kepek/kep1.jpg",
    ar: 1500,
    ertekeles: 4.0,
  },
  {
    nev: "Hortenzia",
    leiras: "Gömb alakú virágzat, sok színben.",
    kep: "kepek/kep1.jpg",
    ar: 6500,
    ertekeles: 4.6,
  },
  {
    nev: "Petúnia",
    leiras: "Balkonnövény, bőséges virágzással.",
    kep: "kepek/kep1.jpg",
    ar: 2200,
    ertekeles: 4.2,
  },
  {
    nev: "Begónia",
    leiras: "Árnyéktűrő dísznövény.",
    kep: "kepek/kep1.jpg",
    ar: 2700,
    ertekeles: 4.1,
  },
  {
    nev: "Írisz",
    leiras: "Elegáns formájú virág.",
    kep: "kepek/kep1.jpg",
    ar: 4800,
    ertekeles: 4.5,
  },
  {
    nev: "Kála",
    leiras: "Letisztult, modern megjelenés.",
    kep: "kepek/kep1.jpg",
    ar: 5300,
    ertekeles: 4.6,
  },
  {
    nev: "Futó muskátli",
    leiras: "Erkélyládába ideális növény.",
    kep: "kepek/kep1.jpg",
    ar: 2400,
    ertekeles: 4.3,
  },
  {
    nev: "Zinnia",
    leiras: "Színes nyári virág.",
    kep: "kepek/kep1.jpg",
    ar: 2100,
    ertekeles: 4.2,
  },
  {
    nev: "Dália",
    leiras: "Gazdag színválaszték, nagy virágok.",
    kep: "kepek/kep1.jpg",
    ar: 3700,
    ertekeles: 4.5,
  },
  {
    nev: "Freesia",
    leiras: "Illatos, elegáns virág.",
    kep: "kepek/kep1.jpg",
    ar: 4100,
    ertekeles: 4.4,
  },
  {
    nev: "Kamélia",
    leiras: "Téli virágzású dísznövény.",
    kep: "kepek/kep1.jpg",
    ar: 7800,
    ertekeles: 4.7,
  },
  {
    nev: "Anemóna",
    leiras: "Finom szirmú tavaszi virág.",
    kep: "kepek/kep1.jpg",
    ar: 3300,
    ertekeles: 4.3,
  },
];
